---

- name: Enable selinux
  selinux:
    policy="targeted"
    state="enforcing"
  when: mode == "pre"

- name: Collect All Backnets By Group
  set_fact: {"{{ item | regex_replace('-', '_') }}_backnet_addrs":"{{ groups[item] | map('extract', hostvars, ['backnet_addr']) | list }}"}
  with_items: "{{ groups }}"
  when: mode == "pre"
  run_once: true

- name: Collect All Frontnets By Group
  set_fact: {"{{ item | regex_replace('-', '_') }}_frontnet_addrs":"{{ groups[item] | map('extract', hostvars, ['frontnet_addr']) | list }}"}
  with_items: "{{ groups }}"
  when: mode == "pre"
  run_once: true
