---
- include: lb-all.yml

- name: Reformat external Dicts For HAProxy (with varnish)
  set_fact:
    haproxy_external_servers="{{ haproxy_external_servers | default([]) + [ dict(name=item1,ip=item1,port=varnish_port,params=[]) ] }}"
  with_items: "{{ lb_varnish_backnet_addrs }}"
  loop_control:
    loop_var: "item1"
  when:
    - mode == "pre"    
    - lb_varnish_backnet_addrs is defined
  run_once: true

- name: Reformat external Dicts For HAProxy (without varnish)
  set_fact:
    haproxy_external_servers="{{ haproxy_external_servers | default([]) + [ dict(name=item2,ip=item2,port=varnish_port,params=[]) ] }}"
  with_items: "{{ lb_web_backnet_addrs }}"
  loop_control:
    loop_var: "item2"
  when:
    - mode == "pre"    
    - lb_varnish_backnet_addrs is not defined
  run_once: true

- name: Allow Haproxy To Bind On Port haproxy stats port
  seport:
    ports="{{ haproxy_stats_port }}"
    proto="tcp"
    setype="http_port_t"
    state="present"
  when: mode == "pre"
