---

- name: Reformat FPM Dicts For HAProxy
  set_fact:
    haproxy_fpm_servers="{{ haproxy_fpm_servers | default([]) + [ dict(name=item,ip=item,port=php_fpm_port,params=[]) ] }}"
  with_items: "{{ fpm_backnet_addrs }}"
  when: mode == "pre"
  run_once: true

- name: Allow Haproxy To Bind On Port haproxy stats port
  seport:
    ports="{{ haproxy_stats_port }}"
    proto="tcp"
    setype="http_port_t"
    state="present"
  when: mode == "pre"
