---
- include: lb-all.yml
  tags: "lb"

- name: Reformat varnish Dicts For HAProxy
  set_fact:
    haproxy_varnish_servers="{{ haproxy_varnish_servers | default([]) + [ dict(name=ip_item,ip=ip_item,port=varnish_port,params=[]) ] }}"
  with_items: "{{ varnish_backnet_addrs }}"
  loop_control:
    loop_var: ip_item
  tags: "lb"
  when: mode == "pre"
  run_once: true

- name: Allow Haproxy To Bind On Port haproxy stats port
  seport:
    ports="{{ haproxy_stats_port }}"
    proto="tcp"
    setype="http_port_t"
    state="present"
  tags: "lb"
  when: mode == "pre"
