---

- name: Reformat Webserver Dicts For HAProxy
  set_fact:
    haproxy_web_servers="{{ haproxy_web_servers | default([]) + [ dict(name=item,ip=item,port=web_port,params=[]) ] }}"
  with_items: "{{ web_backnet_addrs }}"
  when: mode == "pre"
  run_once: true

- name: Allow Haproxy To Bind On Port haproxy stats port
  seport:
    ports="{{ haproxy_stats_port }}"
    proto="tcp"
    setype="http_port_t"
    state="present"
  when: mode == "pre"

- name: Allow Haproxy To Bind On Backend Web Port
  seport:
    ports="{{ web_port }}"
    proto="tcp"
    setype="http_port_t"
    state="present"
  when: mode == "pre"
