---

- name: Application Stop
  script:
    application-stop.sh

- name: Unmount
  script:
    unmount-app-root.sh {{ nex_app_root }}
  register: result

- name: Mount Build ID
  mount:
    opts="{{ nex_app_build_mount_opts }}"
    fstype="none"
    state="mounted"
    name="{{ nex_app_root }}"
    src="{{ nex_app_build_code_base }}"

