---
- name: Base Setup
  hosts: all
  become: true
  any_errors_fatal: true
  pre_tasks:
    - include: tasks/all.yml mode="pre"
  roles:
    - nexcess.server
    - { role: nexcess.puppet, when: "nex_env_target is undefined or nex_env_target != 'vagrant'" }
  post_tasks:
    - include: tasks/all.yml mode="post"

