---
- name: Setup Fileserver
  hosts: fs
  become: true
  any_errors_fatal: true
  pre_tasks:
    - include: tasks/fs.yml mode="pre"
  roles:
    - nexcess.nfs
  post_tasks:
    - include: tasks/fs.yml mode="post"

