---

- name: Setup Redis Load Balancer
  hosts: lb-redis
  become: true
  pre_tasks:
    - include: tasks/lb-redis.yml mode="pre"
  roles:
    - nexcess.haproxy
    - { role: "{{ nex_app }}", mode: "env" }
  post_tasks:
    - include: tasks/lb-redis.yml mode="post"

