---

- name: Setup Web Load Balancer
  hosts: lb-web
  become: true
  pre_tasks:
    - include: tasks/lb-web.yml mode="pre"
  roles:
    - nexcess.haproxy
    - { role: "{{ nex_app }}", mode: "env" }
  post_tasks:
    - include: tasks/lb-web.yml mode="post"

