---

- name: Setup Varnish Load Balancer
  hosts: lb-varnish
  become: true
  pre_tasks:
    - include: tasks/lb-varnish.yml mode="pre"
  roles:
    - nexcess.haproxy
  post_tasks:
    - include: tasks/lb-varnish.yml mode="post"

