---

- name: Setup FPM Load Balancer
  hosts: lb-fpm
  become: true
  pre_tasks:
    - include: tasks/lb-fpm.yml mode="pre"
  roles:
    - nexcess.haproxy
    - { role: "{{ nex_app }}", mode: "env" }
  post_tasks:
    - include: tasks/lb-fpm.yml mode="post"

