---

- name: Setup External Load Balancer
  hosts: lb-external
  become: true
  pre_tasks:
    - include: tasks/lb-external.yml mode="pre"
  roles:
    - nexcess.ssl-cert
    - nexcess.haproxy
    - { role: "{{ nex_app }}", mode: "env" }
  post_tasks:
    - include: tasks/lb-external.yml mode="post"
