---

- name: Setup Varnish
  hosts: varnish
  become: true
  pre_tasks:
    - include: tasks/varnish.yml mode="pre"
  roles:
    - nexcess.varnish
    - { role: "{{ nex_app }}", mode: "env" }
  post_tasks:
    - include: tasks/varnish.yml mode="post"

