---

- name: Deploy Application
  hosts: fs
  become: true
  any_errors_fatal: true
  pre_tasks:
    - include: tasks/all.yml mode="pre"
  roles:
    - { role: "{{ nex_app }}", mode: "deploy" }
  post_tasks:
    - include: tasks/all.yml mode="post"
