---

- name: Deploy An Application Build
  hosts: fpm:web:fs
  become: true
  any_errors_fatal: true
  pre_tasks:
    - include: tasks/all.yml mode="pre"
    - include: tasks/deploy/pre.yml

  roles:
    - { role: "{{ nex_app }}", mode: "deploy" }
 
  post_tasks:    
    - include: tasks/deploy/post.yml
