---

- name: Deploy SQL File
  hosts: db
  become: true
  any_errors_fatal: true
  pre_tasks:
    - include: tasks/all.yml mode="pre"
  tasks:
    - include: tasks/db/deploy.yml
  post_tasks:
    - include: tasks/all.yml mode="post"
